/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Noufhamza
 */
public class main extends javax.swing.JFrame {

    int triesCount = 0;
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hiddenNumLabel = new javax.swing.JLabel();
        hiddenNumF = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        guessNumF = new javax.swing.JTextField();
        guessNumBtn = new javax.swing.JButton();
        resultLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hiddenNumLabel.setText("Hidden Number:");

        hiddenNumF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiddenNumFActionPerformed(evt);
            }
        });

        jLabel2.setText("Guessed Number:");

        guessNumF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessNumFActionPerformed(evt);
            }
        });

        guessNumBtn.setText("Guess");
        guessNumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessNumBtnActionPerformed(evt);
            }
        });

        resultLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guessNumBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(resultLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hiddenNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hiddenNumF)
                                .addComponent(guessNumF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiddenNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hiddenNumF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(guessNumF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guessNumBtn)
                .addGap(18, 18, 18)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hiddenNumFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiddenNumFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hiddenNumFActionPerformed

    private void guessNumFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessNumFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessNumFActionPerformed

    private void resultLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultLabelActionPerformed

    private void guessNumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessNumBtnActionPerformed
        // TODO add your handling code here:
        char[] hiddenNumChar = hiddenNumF.getPassword();
        String hiddenNumString = "";
        
        for(int i = 0; i < hiddenNumChar.length; i++){
            hiddenNumString += hiddenNumChar[i];
        }
        
        
        //////////////////////////////////////////////////////////
        // TRY / CATCH EXCEPTION FOR INTEGER CHECK
        /*try {
            int hiddenNum = Integer.parseInt(hiddenNumString); 
            
        } catch (NumberFormatException e) {
            System.out.println("Please input an integer.");
        }
        
        String guessNumStr = guessNumF.getText();
        try {
            int guessNum = Integer.parseInt(guessNumStr); 
        } catch (NumberFormatException e) {
            System.out.println("Please input an integer.");
        }**/
        ////////////////////////////////////////////////////////
        
        int hiddenNum = Integer.parseInt(hiddenNumString); 
        String guessNumStr = guessNumF.getText();
        int guessNum = Integer.parseInt(guessNumStr); 
        
        if (guessNum == hiddenNum) {
            resultLabel.setText("You Win!");
        } else if(triesCount < 6) {
            triesCount++;
            System.out.println(triesCount);
            if (guessNum < hiddenNum)
            {
                resultLabel.setText("The hidden number is bigger");
            } else {
                resultLabel.setText("The hidden number is smaller.");
            } 
        } else {
            resultLabel.setText("You lose!");
        }
        
    }//GEN-LAST:event_guessNumBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guessNumBtn;
    private javax.swing.JTextField guessNumF;
    private javax.swing.JPasswordField hiddenNumF;
    private javax.swing.JLabel hiddenNumLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultLabel;
    // End of variables declaration//GEN-END:variables
}
